services:
  equipment-management:
    image: paulwoods/equipment-management:latest
    ports:
      - "3000:3000"
    environment:
      - APP_DATA_DIR=data
    volumes:
      - ./data:/app/data
    restart: always
