services:
  postgres:
    image: postgres:18
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    image: paulwoods/equipment-backend:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: paulwoods/equipment-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
